### PR TITLE
Tamagui theme

### LINKED ISSUE #15: Add a proper tamagui theme
https://tamagui.dev/theme

### PR DESCRIPTION
**Pull request by dotellie**
So this took significantly longer than I expected 😅 Either way, it's done now and before you get your pre-requisite copilot generated description, I would like to quickly mention that from now on, `Button`, `Input` and `TextArea` should be imported from the project local files and **not** Tamagui. I think it's the easiest way to stay consistent with styling, but there's probably an easier way using the themes more properly. But yeah, here's copilot:

---

This pull request includes various changes across multiple files to improve theme integration, refactor components, and enhance the user interface. The most important changes are grouped by theme below:

### Theme Integration and UI Enhancements:
* [`app/(tabs)/_layout.tsx`](diffhunk://#diff-ea7f70dea9b63c4fcf80ad308f46fc316bfd05e41531a2a44dd56e1ea215a637R4-R39): Integrated `useTheme` from `tamagui` to dynamically set colors and styles for the tab bar and scene background.
* [`app/_layout.tsx`](diffhunk://#diff-a297596ca5a79abd3db7509592a07106f1c27c02ee55895a4dee8bcce9f7da57R3-R35): Applied theme colors to the system UI background and stack screen options using `useEffect` and `useColorScheme` hooks.
* [`app/eventCreation/_layout.tsx`](diffhunk://#diff-692f6ed57e3c86ead0097d1bf0b891860dfb7895d0c313cdf65775d65b35a4c9R2-R16): Added `useTheme` to set the background color for the event creation layout.
* [`app/eventPage/_layout.tsx`](diffhunk://#diff-692f6ed57e3c86ead0097d1bf0b891860dfb7895d0c313cdf65775d65b35a4c9R2-R16): Utilized `useTheme` to set the background color for the event page layout.
* [`app/joinEvent/_layout.tsx`](diffhunk://#diff-441c9766bbf5c690cb28f0814dd95c983aab9685dd2046ccdd5263354b9edac8R2-R15): Integrated `useTheme` to apply theme-based background color for the join event layout.

### Component Refactoring:
* [`app/eventCreation/index.tsx`](diffhunk://#diff-64cfe9a8985d4c468d9d4b165a4ed16d1f90b84904fc6fb0f3e7b5b27eebba19L12-R19): Refactored imports to use custom components (`Button`, `FloatingActionButton`, `TextArea`) and removed redundant `View` wrappers. [[1]](diffhunk://#diff-64cfe9a8985d4c468d9d4b165a4ed16d1f90b84904fc6fb0f3e7b5b27eebba19L12-R19) [[2]](diffhunk://#diff-64cfe9a8985d4c468d9d4b165a4ed16d1f90b84904fc6fb0f3e7b5b27eebba19L91-R87) [[3]](diffhunk://#diff-64cfe9a8985d4c468d9d4b165a4ed16d1f90b84904fc6fb0f3e7b5b27eebba19L116-L118) [[4]](diffhunk://#diff-64cfe9a8985d4c468d9d4b165a4ed16d1f90b84904fc6fb0f3e7b5b27eebba19L130-R128) [[5]](diffhunk://#diff-64cfe9a8985d4c468d9d4b165a4ed16d1f90b84904fc6fb0f3e7b5b27eebba19L147-R148) [[6]](diffhunk://#diff-64cfe9a8985d4c468d9d4b165a4ed16d1f90b84904fc6fb0f3e7b5b27eebba19L163-L172) [[7]](diffhunk://#diff-64cfe9a8985d4c468d9d4b165a4ed16d1f90b84904fc6fb0f3e7b5b27eebba19L181-R183)
* `app/eventPage/[id].tsx`: Replaced `Button` with `FloatingActionButton` and updated icon colors to use theme variables. ([app/eventPage/[id].tsxL3-R5](diffhunk://#diff-81a951083e257f138cb65acfee6e678532015fa5f1537a80a8987626ec013a34L3-R5), [app/eventPage/[id].tsxR32-R45](diffhunk://#diff-81a951083e257f138cb65acfee6e678532015fa5f1537a80a8987626ec013a34R32-R45), [app/eventPage/[id].tsxL52-R54](diffhunk://#diff-81a951083e257f138cb65acfee6e678532015fa5f1537a80a8987626ec013a34L52-R54), [app/eventPage/[id].tsxL71-R86](diffhunk://#diff-81a951083e257f138cb65acfee6e678532015fa5f1537a80a8987626ec013a34L71-R86))

### Form Validation and Submission:
* [`app/joinEvent/attendeeDetails.tsx`](diffhunk://#diff-3dfe4ead7642e50da4fccba1ae8712f44cf3cc876383a6cc494cc60ad92c070bR1-R42): Added `zod` schema validation for form fields and used `zodResolver` with `react-hook-form` for validation. Replaced `Button` with `FloatingActionButton` for form submission. [[1]](diffhunk://#diff-3dfe4ead7642e50da4fccba1ae8712f44cf3cc876383a6cc494cc60ad92c070bR1-R42) [[2]](diffhunk://#diff-3dfe4ead7642e50da4fccba1ae8712f44cf3cc876383a6cc494cc60ad92c070bL45-R66) [[3]](diffhunk://#diff-3dfe4ead7642e50da4fccba1ae8712f44cf3cc876383a6cc494cc60ad92c070bR75-R76) [[4]](diffhunk://#diff-3dfe4ead7642e50da4fccba1ae8712f44cf3cc876383a6cc494cc60ad92c070bR85-R87) [[5]](diffhunk://#diff-3dfe4ead7642e50da4fccba1ae8712f44cf3cc876383a6cc494cc60ad92c070bL75-R114)

### ESLint Configuration:
* [`.eslintrc.js`](diffhunk://#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5L10-R21): Updated `ignorePatterns` to include `theme-output.ts` and modified the `spaced-comment` rule to allow specific markers.

Fixes #15

### CODE REVIEW

**Comment by ssheloors** [comment]
The code input in ```joinEvent``` is not working anymore, could it be because of the change from ```<Text>``` to ```<Input>``` ? 🤔 

image

**Comment by ssheloors** [comment]
Wait, I tried it on the android emulator and it doesn't crash there, so apparently it's just a web issue

**Comment by dotellie** [comment]
Huh that's strange! I feel like we should have it working on web as well even though mobile is our main target, so I'll take a look and see if we can easily fix this. Thank you for pointing out the issue!

**Comment by dotellie** [comment]
@ssheloors That issue should be fixed now! Made me go down quite a deep rabbit hole though and coming out the other side once again kind of hating Tamagui, but I suppose it being fixed is what matters 😂

**Comment by ssheloors** [comment]
Merging!! Good job 🏅

**Pull request merged**
